---

- hosts: all
  gather_facts: false
  remote_user: root
  tasks:

    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Ensure python is available
      raw: test -e /usr/bin/python || apt install -y --allow-unauthenticated python-minimal

    - name: Ensure python-apt is available
      raw: test -d /usr/share/python-apt || apt install -y --allow-unauthenticated python-apt

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade

- hosts: mcs
  remote_user: root
  tasks:

    - name: Install openjdk
      apt:
        name: openjdk-9-jre
        state: present
        allow_unauthenticated: yes

    - name: Install screen
      apt:
        name: screen
        state: present
        allow_unauthenticated: yes

    - name: Create /usr/local/minecraft
      file:
        path: /usr/local/minecraft
        recurse: yes
        state: directory

    - name: Download minecraft server
      get_url:
        url: https://launcher.mojang.com/mc/game/1.12.2/server/886945bfb2b978778c3a0288fd7fab09d315b25f/server.jar
        dest: /usr/local/minecraft/server.jar

    - name: Copy server.properties
      template:
        src: files/server.properties
        dest: /usr/local/minecraft/server.properties
      register: config

    - name: Copy eula.txt
      template:
        src: files/eula.txt
        dest: /usr/local/minecraft/eula.txt

    - name: Install rc.local
      template:
        src: files/rc.local
        dest: /etc/rc.local
        mode: 755

    - name: Finally run rc.local
      command: /etc/rc.local
